# -*- coding: utf-8 -*-
"""Supervised_outlier_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1r0RHhFV2a3UkFD8dAktunM1qQTCVeS
"""

"""
Tier-2 QC — supervised classification (LogReg, RandomForest, XGBoost).
Metrics reported as mean +/- 95% CI over repeated group-aware CV.
Data: MEA_data_consensus_training_vote2.csv
"""

# =============================================================================
# 1) IMPORTS
# -----------------------------------------------------------------------------

import numpy as np, pandas as pd
from scipy.stats import loguniform, randint, uniform, t
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedGroupKFold, RandomizedSearchCV
from sklearn.metrics import (roc_auc_score, average_precision_score, precision_score,
                             recall_score, f1_score, matthews_corrcoef, log_loss)
from xgboost import XGBClassifier

N_ITER  = 25                      # random-search budget: configs tried per inner fold
REPEATS = 5                       # repeats of the whole CV -> confidence intervals

# =============================================================================
# 2) LOAD THE LABELLED DATA
# -----------------------------------------------------------------------------

d = pd.read_csv("MEA_data_consensus_training_vote2.csv")
#d = d[d.QC_low_activity == "pass"].reset_index(drop=True)

# =============================================================================
# 3) DEFINE THE LABEL, THE FEATURES, AND THE GROUP (leakage) ID
# =============================================================================

META = ["Barcode", "Plate", "Timepoint_dpp", "Well", "Control", "QC_low_activity", "qc_fail"]
feats = [c for c in d.columns if c not in META and pd.api.types.is_numeric_dtype(d[c])]
y = (d["qc_fail"].astype(str) == "1").astype(int).to_numpy()                         # 1 = fail (minority)
g = d[["Barcode", "Plate", "Timepoint_dpp"]].astype(str).agg("|".join, 1).to_numpy()

# =============================================================================
# 4) HANDLE THE MISSING BURST FEATURES CORRECTLY
# The network-burst features are NaN when a well never network-bursted — that is
# real biology, not missing-at-random. So we DON'T impute a median: we add a
# 'bursted' flag (1/0) and set the burst columns to 0 ("no bursts").
# =============================================================================

burst = [c for c in feats if d[c].isna().any()]
d["bursted"] = d[burst[0]].notna().astype(int)          # 1 = the well network-bursted
d[burst] = d[burst].fillna(0.0)                         # no bursts -> 0
feats = feats + ["bursted"]

# =============================================================================
# 5) BUILD THE MODEL INPUTS
# -----------------------------------------------------------------------------
# X: the feature matrix. spw: XGBoost's imbalance weight = #pass / #fail.
# =============================================================================
X = d[feats].to_numpy(float)
spw = (y == 0).sum() / y.sum()

# =============================================================================
# 6) THREE MODELS + THEIR HYPERPARAMETER SEARCH SPACES
# -----------------------------------------------------------------------------
# Imbalance is handled by CLASS WEIGHTS in every model (up-weight the rare 'fail').
# LogReg: Yeo-Johnson removes the skew, StandardScaler then centres/scales; trees
#         skip this — they are invariant to monotonic transforms.
# The dictionaries are the ranges/values the search will sample (regularisation-focused).
# =============================================================================
models = {
 "LogReg": (Pipeline([("power", PowerTransformer("yeo-johnson", standardize=False)),
                      ("scale", StandardScaler()),
                      ("clf", LogisticRegression(class_weight="balanced", solver="liblinear"))]),
            {"clf__C": loguniform(1e-3, 1e2),           # regularisation strength
             "clf__penalty": ["l1", "l2"]}),            # feature-selecting vs smooth shrinkage
 "RandomForest": (Pipeline([("clf", RandomForestClassifier(
                      n_estimators=500, class_weight="balanced_subsample", random_state=42))]),
            {"clf__max_depth": [None, 3, 5, 8, 12],      # overfitting control
             "clf__min_samples_leaf": randint(1, 8),     # leaf size (smoothing)
             "clf__max_features": ["sqrt", "log2", 0.5, 0.7]}),  # decorrelation per split
 "XGBoost": (Pipeline([("clf", XGBClassifier(scale_pos_weight=spw,
                                             eval_metric="logloss", random_state=42))]),
            {"clf__n_estimators": [300, 600],            # boosting rounds
             "clf__learning_rate": loguniform(0.02, 0.3),# step size per tree
             "clf__max_depth": randint(2, 6),            # shallow trees
             "clf__min_child_weight": randint(1, 8),     # conservative splits
             "clf__subsample": uniform(0.6, 0.4),        # rows per tree (0.6-1.0)
             "clf__colsample_bytree": uniform(0.6, 0.4), # features per tree (0.6-1.0)
             "clf__reg_lambda": loguniform(1e-3, 10)}),  # L2 on leaf weights
}

# =============================================================================
# 7) NESTED, GROUP-AWARE CROSS-VALIDATION  (the honest train/test evaluation)
# -----------------------------------------------------------------------------
# OUTER loop: train on some recordings, PREDICT the held-out recordings the model
#             never saw -> no plate/timepoint leakage.
# INNER loop: RandomizedSearchCV tunes hyper-parameters using ONLY the training
#             recordings, so the reported score isn't inflated by tuning on test.
# The partition is SHUFFLED per repeat (random_state=rep) so repeating the whole
# procedure gives an honest spread -> confidence intervals.
# =============================================================================
def oof_predictions(estimator, space, rep):
    proba = np.zeros(len(y))
    cv = StratifiedGroupKFold(3, shuffle=True, random_state=rep)
    for train, test in cv.split(X, y, g):                            # outer split
        inner = StratifiedGroupKFold(3, shuffle=True, random_state=rep)
        search = RandomizedSearchCV(estimator, space, n_iter=N_ITER,
                                    scoring="average_precision",       # optimise PR-AUC
                                    cv=inner, random_state=rep, n_jobs=-1)
        search.fit(X[train], y[train], groups=g[train])               # inner: tune on train
        proba[test] = search.predict_proba(X[test])[:, 1]             # predict held-out wells
    return proba

# =============================================================================
# 8) METRICS  (chosen for an IMBALANCED problem)
# -----------------------------------------------------------------------------
# PR-AUC & ROC-AUC are threshold-free (judge the ranking); precision/recall/F1/MCC
# are at the 0.5 cut-off. We avoid plain accuracy: predicting "pass" for everything
# would already score ~82% here yet catch zero fails.
# =============================================================================
def scores(y_true, proba, thr=0.5):
    pred = (proba >= thr).astype(int)
    return dict(ROC_AUC=roc_auc_score(y_true, proba),
                PR_AUC=average_precision_score(y_true, proba),
                Precision=precision_score(y_true, pred, zero_division=0),
                Recall=recall_score(y_true, pred, zero_division=0),
                F1=f1_score(y_true, pred, zero_division=0),
                MCC=matthews_corrcoef(y_true, pred),
                LogLoss=log_loss(y_true, proba))          # <- added: calibration, lower is better
# =============================================================================
# 9) RUN AND REPORT  (repeat the whole CV, report mean +/- 95% CI)
# -----------------------------------------------------------------------------
# Each repeat re-runs the full nested CV with a different shuffled partition; we
# collect the per-repeat metrics and summarise each as a mean and 95% CI.
# =============================================================================
def mean_ci(v):                                   # mean and 95% CI half-width (t-based)
    v = np.asarray(v)
    h = t.ppf(.975, len(v)-1) * v.std(ddof=1) / np.sqrt(len(v)) if len(v) > 1 else 0.0
    return v.mean(), h

rows = {}
for name, (est, space) in models.items():
    per_repeat = pd.DataFrame([scores(y, oof_predictions(est, space, rep)) for rep in range(REPEATS)])
    rows[name] = {m: f"{mean_ci(per_repeat[m])[0]:.3f} +/- {mean_ci(per_repeat[m])[1]:.3f}"
                  for m in per_repeat.columns}

table = pd.DataFrame(rows).T
print(f"Metrics as mean +/- 95% CI over {REPEATS} repeats (group-aware CV)\n")
print(table.to_string())
table.to_csv("supervised_metrics_v2.csv")

# =============================================================================
# TUNING ANALYSIS — open up the hyperparameter search (for the results section)
# -----------------------------------------------------------------------------
# The nested CV above gives the HONEST performance (mean +/- CI). Here we run ONE
# final group-aware search per model on ALL the data, to (a) report the winning
# settings used for the deployed model and (b) show how the configurations compared.
# NOTE: mean_test_score here is the INNER selection score (optimistic) — use it to
# COMPARE settings, not as the headline performance (that stays the nested-CV table).
# =============================================================================
tuning_cv = StratifiedGroupKFold(3, shuffle=True, random_state=0)

for name, (est, space) in models.items():
    s = RandomizedSearchCV(est, space, n_iter=N_ITER, scoring="average_precision",
                           cv=tuning_cv, random_state=0, n_jobs=-1)
    s.fit(X, y, groups=g)

    res = pd.DataFrame(s.cv_results_)
    pcols = [c for c in res.columns if c.startswith("param_")]
    res = res[pcols + ["mean_test_score", "std_test_score", "rank_test_score"]] \
             .sort_values("rank_test_score")

    print(f"\n===== {name}: configurations compared (PR-AUC, inner selection score) =====")
    print(res.head(5).to_string(index=False))                 # top 5 configurations
    print(f"Winning {name} settings: {s.best_params_}")

    # effect of each hyperparameter on its own (flat = setting barely matters)
    print(f"--- {name}: mean score per hyperparameter value ---")
    for p in pcols:
        print(res.groupby(p)["mean_test_score"].mean().round(3).to_dict())

    res.to_csv(f"tuning_{name}.csv", index=False)             # full table for the appendix

# =======================================================================
# SHAP — Random Forest feature importance (violin plot)
# =======================================================================
import shap

# fit the Random Forest on all labelled wells (same config as evaluated)
rf = RandomForestClassifier(n_estimators=500, class_weight="balanced_subsample", random_state=42)
rf.fit(X, y)

# exact, fast explainer for tree models
explainer = shap.TreeExplainer(rf)
sv = explainer.shap_values(X)

# pick the "fail" class (SHAP's output shape varies by version)
if isinstance(sv, list):        vals = sv[1]            # list: one array per class
elif sv.ndim == 3:              vals = sv[:, :, 1]      # (samples, features, classes)
else:                           vals = sv

shap.summary_plot(vals, X, feature_names=feats, plot_type="violin", show=True)

import matplotlib.pyplot as plt

shap.summary_plot(vals, X, feature_names=feats, plot_type="violin", show=False)
plt.tight_layout()
plt.savefig("shap_rf_violin.png", dpi=300, bbox_inches="tight")   # or .pdf for vector quality
plt.show()