# -*- coding: utf-8 -*-
"""adjusted_boxplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPGPKUQFSbzcIb0ZG6SgDsU_y0KuZ2V7
"""

import numpy as np
import pandas as pd
from statsmodels.stats.stattools import medcouple

MIN_WELLS = 10

def adjusted_fence(x):
    """Adjusted-boxplot lower and upper limits."""
    x = pd.Series(x).dropna().to_numpy(float)
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    mc = float(medcouple(x))
    a, b = (-4, 3) if mc >= 0 else (-3, 4)

    lo = q1 - 1.5 * np.exp(a * mc) * iqr
    hi = q3 + 1.5 * np.exp(b * mc) * iqr

    return lo, hi, mc


wide = pd.read_csv("low_activity_wells_flagged (2).csv")
#good = wide["QC_low_activity"] == "pass"

ids = [
    "Barcode", "Plate", "Timepoint_dpp", "Well", "Control",
    "QC_low_activity", "Adjusted_boxplot_outlier",
    "outlier_features", "n_features_flagged"
]

features = [
    c for c in wide.select_dtypes(include=np.number).columns
    if c not in ids
]

outlier = pd.Series(False, index=wide.index)

low_hits = pd.DataFrame(False, index=wide.index, columns=features)
high_hits = pd.DataFrame(False, index=wide.index, columns=features)

# Store feature limits
bands = []

for (plate, dpp), grp in wide.groupby(["Plate", "Timepoint_dpp"]):

    here = (
        (wide["Plate"] == plate) &
        (wide["Timepoint_dpp"] == dpp)
    )

    for f in features:
        v = grp[f].dropna()

        if len(v) < MIN_WELLS:
            continue

        lo, hi, mc = adjusted_fence(v)

        bands.append({
            "Plate": plate,
            "Timepoint_dpp": dpp,
            "Feature": f,
            "Lower_band": lo,
            "Upper_band": hi,
            "Medcouple": mc,
            "Number_of_wells": len(v)
        })

        current_low = here & (wide[f] < lo)
        current_high = here & (wide[f] > hi)

        low_hits.loc[current_low, f] = True
        high_hits.loc[current_high, f] = True

        outlier |= current_low | current_high


wide["Adjusted_boxplot_outlier"] = "dead_well"
wide.loc[outlier, "Adjusted_boxplot_outlier"] = "yes"
wide.loc[~outlier, "Adjusted_boxplot_outlier"] = "no"

wide["outlier_features"] = [
    "; ".join(
        [f"{f} (low)" for f in features if low_hits.at[i, f]] +
        [f"{f} (high)" for f in features if high_hits.at[i, f]]
    )
    for i in wide.index
]

wide["n_features_flagged"] = (
    low_hits.sum(axis=1) + high_hits.sum(axis=1)
).astype(int)


# Save outlier results
wide.to_csv("adjusted_boxplot_outliers.csv", index=False)


# Create and save lower/upper-band table
bands_df = pd.DataFrame(bands)

bands_df[["Lower_band", "Upper_band", "Medcouple"]] = (
    bands_df[["Lower_band", "Upper_band", "Medcouple"]].round(3)
)

bands_df.to_csv(
    "adjusted_boxplot_feature_bands.csv",
    index=False
)


print(wide["Adjusted_boxplot_outlier"].value_counts().to_string())

# =======================================================================
# Plate-Map Visualisation of Adjusted Boxplot QC code cell
#========================================================================


import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

rows, cols = "ABCDEF", range(1, 9)
groups = wide[["Plate", "Timepoint_dpp"]].drop_duplicates().sort_values(
    ["Plate", "Timepoint_dpp"]
)

fig, axes = plt.subplots(2, 3, figsize=(13, 7))
axes = axes.flatten()

for ax, (_, g) in zip(axes, groups.iterrows()):

    d = wide[
        (wide["Plate"] == g["Plate"]) &
        (wide["Timepoint_dpp"] == g["Timepoint_dpp"])
    ].set_index("Well")

    for y, row in enumerate(rows):
        for x in cols:
            well = f"{row}{x}"

            if well not in d.index:
                colour = "lightgray"
            elif d.loc[well, "Adjusted_boxplot_outlier"] == "dead_well":
                colour = "darkgray"
            elif d.loc[well, "Adjusted_boxplot_outlier"] == "yes":
                colour = "red"
            else:
                colour = "green"

            ax.scatter(x, y, s=550, c=colour, edgecolors="black")

    ax.set(
        title=f"Plate {int(g['Plate'])} — {int(g['Timepoint_dpp'])} dpp",
        xticks=list(cols),
        yticks=range(6),
        yticklabels=list(rows),
        xlim=(0.5, 8.5),
        ylim=(5.5, -0.5)
    )

    ax.xaxis.tick_top()
    ax.set_aspect("equal")
    ax.tick_params(length=0)

legend = [
    Line2D([0], [0], marker="o", color="w", markerfacecolor="green",
           markeredgecolor="black", markersize=12, label="Pass"),
    Line2D([0], [0], marker="o", color="w", markerfacecolor="red",
           markeredgecolor="black", markersize=12, label="Fail"),
    Line2D([0], [0], marker="o", color="w", markerfacecolor="lightgray",
           markeredgecolor="black", markersize=12, label="Not in data"),
    Line2D([0], [0], marker="o", color="w", markerfacecolor="darkgray",
           markeredgecolor="black", markersize=12, label="Dead well")
]

fig.legend(handles=legend, loc="lower center", ncol=4)


fig.suptitle(
    "Adjusted boxplot quality control result",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout(rect=[0, 0.08, 1, 0.95])
fig.subplots_adjust(hspace=0.3)
plt.savefig("Adjusted_boxplot_outlier.png", dpi=150)
plt.show()

import numpy as np
import pandas as pd
from statsmodels.stats.stattools import medcouple

MIN_WELLS = 10
K_VALUES = [1.0, 1.5, 2.0, 2.5, 3.0]


def adjusted_fence(x, k=1.5):
    x = pd.Series(x).dropna().to_numpy(float)
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    mc = float(medcouple(x))
    a, b = (-4, 3) if mc >= 0 else (-3, 4)

    return (
        q1 - k * np.exp(a * mc) * iqr,
        q3 + k * np.exp(b * mc) * iqr,
        mc
    )


wide = pd.read_csv("low_activity_wells_flagged (2).csv")
#good = wide["QC_low_activity"].eq("pass")

exclude = [
    "Barcode", "Plate", "Timepoint_dpp", "Well", "Control",
    "QC_low_activity", "Adjusted_boxplot_outlier",
    "outlier_features", "n_features_flagged"
]

features = [
    c for c in wide.select_dtypes(include=np.number)
    if c not in exclude
]

comparison = []
all_results = []

for k in K_VALUES:

    outlier = pd.Series(False, index=wide.index)
    feature_count = 0

    for (plate, dpp), grp in wide.groupby(
        ["Plate", "Timepoint_dpp"]
    ):
        here = (
            wide["Plate"].eq(plate) &
            wide["Timepoint_dpp"].eq(dpp)
        )

        for feature in features:

            values = grp[feature].dropna()

            if len(values) < MIN_WELLS:
                continue

            lo, hi, mc = adjusted_fence(values, k)

            low = here & wide[feature].lt(lo)
            high = here & wide[feature].gt(hi)
            flagged = low | high

            outlier |= flagged
            feature_count += flagged.sum()

            for i in wide.index[flagged]:
                all_results.append({
                    "K": k,
                    "Plate": plate,
                    "Timepoint_dpp": dpp,
                    "Well": wide.loc[i, "Well"],
                    "Feature": feature,
                    "Value": wide.loc[i, feature],
                    "Direction": "low" if low.loc[i] else "high",
                    "Lower_band": lo,
                    "Upper_band": hi,
                    "Medcouple": mc
                })

    column = f"Adjusted_K_{str(k).replace('.', '_')}"

    wide[column] = "dead_well"
    wide.loc[~outlier, column] = "pass"
    wide.loc[outlier, column] = "fail"

    comparison.append({
        "K": k,
        "Outlier_wells": int(outlier.sum()),
        "Feature_outliers": int(feature_count)
    })


comparison_df = pd.DataFrame(comparison)
results_df = pd.DataFrame(all_results)

wide.to_csv(
    "adjusted_boxplot_K_sensitivity.csv",
    index=False
)

comparison_df.to_csv(
    "adjusted_boxplot_K_comparison.csv",
    index=False
)

results_df.to_csv(
    "adjusted_boxplot_all_K_outliers.csv",
    index=False
)

print(comparison_df)

import plotly.express as px

fig = px.line(
    comparison_df,
    x="K",
    y=["Outlier_wells", "Feature_outliers"],
    markers=True,
    title="Adjusted Boxplot Multiplier Comparison"
)

fig.show()
