# -*- coding: utf-8 -*-
"""deep_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153NXaSFres_MMD6Z83jSwVfl-rJCfNjC
"""

"""Tier-2 QC neural network — improved & honest evaluation.
Requires: pandas scikit-learn scipy tensorflow matplotlib"""
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from scipy import stats
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, matthews_corrcoef, log_loss, precision_score, recall_score
from tensorflow import keras
import tensorflow as tf
tf.config.experimental.enable_op_determinism()

# --- load + keep analysable wells (removes 'dead_well' tier-1 fails) -----------
d = pd.read_csv("MEA_data_consensus_training_vote2.csv")
d = d[d.QC_low_activity == "pass"].reset_index(drop=True)
META  = ["Barcode","Plate","Timepoint_dpp","Well","Control","QC_low_activity","qc_fail"]
feats = [c for c in d.columns if c not in META and pd.api.types.is_numeric_dtype(d[c])]
GROUP = ["Barcode","Plate","Timepoint_dpp"]

# --- burst features NaN = didn't burst: add flag, fill 0 ----------------------
burst = [c for c in feats if d[c].isna().any()]
if burst:
    d["bursted"] = d[burst[0]].notna().astype(int); d[burst] = d[burst].fillna(0.0); feats += ["bursted"]

# --- arrays: X, y (ROBUST text '1'->1 label), g (recording id) ----------------
X = d[feats].to_numpy(float)
y = (d["qc_fail"].astype(str) == "1").astype(int).to_numpy()        # IMPROVED: robust label (no crash on text)
g = d[GROUP].astype(str).agg("|".join, 1).to_numpy()

# --- network: 2 hidden layers, ReLU, dropout+L2, sigmoid, cross-entropy -------
def build(nf, seed, lr=1e-3):
    ki = keras.initializers.HeNormal(seed=seed); reg = keras.regularizers.l2(1e-3)
    m = keras.Sequential([keras.layers.Input((nf,)),
        keras.layers.Dense(16, "relu", kernel_initializer=ki, kernel_regularizer=reg), keras.layers.Dropout(0.2),
        keras.layers.Dense(8, "relu", kernel_initializer=ki, kernel_regularizer=reg), keras.layers.Dropout(0.2),
        keras.layers.Dense(1, "sigmoid", kernel_initializer=ki)])
    m.compile(keras.optimizers.Adam(lr), "binary_crossentropy"); return m        # explicit learning rate

# --- repeated CV with a SHUFFLED group partition each repeat (honest CI) -------
rows = []; oof_sum = np.zeros(len(y))
for seed in range(10):
    keras.utils.set_random_seed(seed)
    cv = StratifiedGroupKFold(3, shuffle=True, random_state=seed)   # IMPROVED: partition varies -> real uncertainty
    oof = np.zeros(len(y))
    for tr, te in cv.split(X, y, g):                               # test on unseen recordings
        pt = PowerTransformer("yeo-johnson").fit(X[tr]); sc = StandardScaler().fit(pt.transform(X[tr]))  # scale on train
        Xtr = sc.transform(pt.transform(X[tr])); Xte = sc.transform(pt.transform(X[te]))
        cw = {0: 1., 1: (y[tr] == 0).sum() / max((y[tr] == 1).sum(), 1)}          # class weights (imbalance)
        perm = np.random.RandomState(seed).permutation(len(Xtr))                  # shuffle -> representative val split
        es = keras.callbacks.EarlyStopping(monitor="val_loss", patience=20,       # IMPROVED: val-based early stopping
                                           restore_best_weights=True)
        m = build(X.shape[1], seed)
        m.fit(Xtr[perm], y[tr][perm], validation_split=0.2, epochs=200, batch_size=16,
              class_weight=cw, verbose=0, callbacks=[es])
        oof[te] = m.predict(Xte, verbose=0).ravel()                # predict held-out wells
    oof_sum += oof
    p = (oof >= 0.5).astype(int)
    rows.append(dict(ROC_AUC=roc_auc_score(y, oof), PR_AUC=average_precision_score(y, oof),
                     Precision=precision_score(y, p, zero_division=0),
                     Recall=recall_score(y, p, zero_division=0),
                     F1=f1_score(y, p, zero_division=0), MCC=matthews_corrcoef(y, p), LogLoss=log_loss(y, oof)))

# --- report mean +/- 95% CI ---------------------------------------------------
R = pd.DataFrame(rows)
print(f"NN on {len(y)} wells ({int(y.sum())} fails), shuffled group-aware CV, mean +/- 95% CI:")
for c in R.columns:
    h = stats.t.ppf(.975, len(R)-1) * R[c].std(ddof=1) / np.sqrt(len(R)); print(f"  {c:9s} {R[c].mean():.3f} +/-{h:.3f}")

# --- REPORT: save per-well predictions and per-repeat metrics -----------------
rep = d[["Barcode","Plate","Timepoint_dpp","Well"]].copy()
rep["qc_fail_true"] = y
rep["fail_prob"] = (oof_sum / len(R)).round(3)                     # mean predicted prob over repeats
rep["pred_fail"] = (rep["fail_prob"] >= 0.5).astype(int)
rep.sort_values("fail_prob", ascending=False).to_csv("nn_predictions_v2.csv", index=False)
R.round(4).to_csv("nn_metrics_per_repeat_v2.csv", index=False)

# --- ONE illustrative training curve (trained once, OUTSIDE the CV loop) ------
pt = PowerTransformer("yeo-johnson").fit(X); Xs = StandardScaler().fit_transform(pt.transform(X))
cw = {0: 1., 1: (y == 0).sum() / max((y == 1).sum(), 1)}
perm = np.random.RandomState(0).permutation(len(Xs))
demo = build(X.shape[1], 0)
hist = demo.fit(Xs[perm], y[perm], validation_split=0.2, epochs=200, batch_size=16, class_weight=cw, verbose=0,
                callbacks=[keras.callbacks.EarlyStopping(monitor="val_loss", patience=20, restore_best_weights=True)])
plt.plot(hist.history["loss"], label="train loss"); plt.plot(hist.history["val_loss"], label="val loss")
plt.xlabel("epoch"); plt.ylabel("loss"); plt.legend(); plt.title("Illustrative training curve")
plt.savefig("nn_loss_curve_v2.png", dpi=150, bbox_inches="tight"); plt.show()
print("saved nn_predictions.csv, nn_metrics_per_repeat.csv, nn_loss_curve.png")

# =======================================================================
# SHAP - Neural network feature importance (violin plot)
# =======================================================================
import shap

# preprocess ALL wells exactly as in training (Yeo-Johnson + scale)
pt_all = PowerTransformer("yeo-johnson").fit(X)
X_all  = StandardScaler().fit(pt_all.transform(X)).transform(pt_all.transform(X))

# final network on all labelled wells (inlined so cell order can't swap architectures)
def build_nn(nf, seed, layers=(16, 8)):                       # <- set adopted layers here
    ki = keras.initializers.HeNormal(seed=seed); reg = keras.regularizers.l2(1e-3)
    L = [keras.layers.Input((nf,))]
    for u in layers:
        L += [keras.layers.Dense(u, "relu", kernel_initializer=ki, kernel_regularizer=reg),
              keras.layers.Dropout(0.2)]
    L += [keras.layers.Dense(1, "sigmoid", kernel_initializer=ki)]
    m = keras.Sequential(L); m.compile(keras.optimizers.Adam(1e-3), "binary_crossentropy"); return m

keras.utils.set_random_seed(0)
cw = {0: 1., 1: (y == 0).sum() / max((y == 1).sum(), 1)}
es = keras.callbacks.EarlyStopping(monitor="val_loss", patience=20, restore_best_weights=True)
perm = np.random.RandomState(0).permutation(len(X_all))       # FIX: shuffled val split
nn = build_nn(X.shape[1], seed=0)
nn.fit(X_all[perm], y[perm], validation_split=0.2, epochs=200, batch_size=16,
       class_weight=cw, verbose=0, callbacks=[es])

# SHAP on the transformed inputs (the network only ever sees these)
bg = X_all[np.random.RandomState(0).choice(len(X_all), min(50, len(X_all)), replace=False)]
try:
    sv = shap.DeepExplainer(nn, bg).shap_values(X_all)
except Exception:
    sv = shap.GradientExplainer(nn, bg).shap_values(X_all)    # fallback for newer TF
vals = sv[0] if isinstance(sv, list) else sv
if vals.ndim == 3: vals = vals[:, :, 0]
assert vals.shape == X_all.shape                              # safety net

# violin summary + save
shap.summary_plot(vals, X_all, feature_names=feats, plot_type="violin", show=False)
plt.title("Neural network: SHAP impact on P(fail)", fontsize=11)
plt.savefig("shap_nn_violin.png", dpi=300, bbox_inches="tight")
plt.show()

# =============================================================================
# NEURAL-NETWORK TUNING - one-at-a-time exploration around the base config.
# 13 configurations (base + 12 variants), each evaluated with REPEATS=3
# repeats of the shuffled group-aware CV (screening budget). Results are
# written to CSV after EVERY config, so nothing is lost mid-run.
# The winner should then be re-run with the full 10-repeat cell for the
# headline numbers. Expects X, y, g from the data cell above.
# =============================================================================
import numpy as np, pandas as pd
from scipy.stats import t
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import (roc_auc_score, average_precision_score, precision_score,
                             recall_score, f1_score, matthews_corrcoef, log_loss)
from tensorflow import keras

REPEATS = 10                                   # screening repeats per config (winner gets 10 later)

# --- the grid: base config + one-at-a-time variants (matches Table tab:nnconfig) ---
BASE = dict(layers=(32, 16), dropout=0.2, l2=1e-3, lr=1e-3, batch=16)
GRID = {"layers": [(16, 8), (64, 32)],
        "dropout": [0.0, 0.4],
        "l2":      [1e-4, 1e-2],
        "lr":      [1e-4, 1e-2],
        "batch":   [8, 32]}

CONFIGS = [("base", dict(BASE))]
for knob, vals in GRID.items():
    for v in vals:
        cfg = dict(BASE); cfg[knob] = v
        CONFIGS.append((f"{knob}={v}", cfg))                 # e.g. "dropout=0.4"
CONFIGS = [n for n in CONFIGS if n[0] == "layers=(16, 8)"]
# --- parameterised network (same shape as the base build(), knobs exposed) ---
def build(nf, seed, layers, dropout, l2, lr):
    ki = keras.initializers.HeNormal(seed=seed); reg = keras.regularizers.l2(l2)
    L = [keras.layers.Input((nf,))]
    for units in layers:
        L += [keras.layers.Dense(units, "relu", kernel_initializer=ki, kernel_regularizer=reg),
              keras.layers.Dropout(dropout)]
    L += [keras.layers.Dense(1, "sigmoid", kernel_initializer=ki)]
    m = keras.Sequential(L)
    m.compile(keras.optimizers.Adam(lr), "binary_crossentropy")
    return m

def mean_ci(v):                                # mean and 95% CI half-width (t-based)
    v = np.asarray(v, float)
    h = t.ppf(.975, len(v)-1) * v.std(ddof=1) / np.sqrt(len(v)) if len(v) > 1 else 0.0
    return v.mean(), h

# --- one config = repeated shuffled group-aware CV, identical to the main harness ---
def evaluate_config(cfg):
    per_repeat = []
    for seed in range(REPEATS):
        keras.utils.set_random_seed(seed)
        cv = StratifiedGroupKFold(3, shuffle=True, random_state=seed)
        oof = np.zeros(len(y))
        for tr, te in cv.split(X, y, g):                                   # test on unseen recordings
            pt = PowerTransformer("yeo-johnson").fit(X[tr])                # fitted on train fold only
            sc = StandardScaler().fit(pt.transform(X[tr]))
            Xtr = sc.transform(pt.transform(X[tr])); Xte = sc.transform(pt.transform(X[te]))
            cw = {0: 1., 1: (y[tr] == 0).sum() / max((y[tr] == 1).sum(), 1)}
            perm = np.random.RandomState(seed).permutation(len(Xtr))       # representative val split
            es = keras.callbacks.EarlyStopping(monitor="val_loss", patience=20,
                                               restore_best_weights=True)
            m = build(X.shape[1], seed, cfg["layers"], cfg["dropout"], cfg["l2"], cfg["lr"])
            m.fit(Xtr[perm], y[tr][perm], validation_split=0.2, epochs=200,
                  batch_size=cfg["batch"], class_weight=cw, verbose=0, callbacks=[es])
            oof[te] = m.predict(Xte, verbose=0).ravel()
        p = (oof >= 0.5).astype(int)
        per_repeat.append(dict(ROC_AUC=roc_auc_score(y, oof), PR_AUC=average_precision_score(y, oof),
                               Precision=precision_score(y, p, zero_division=0),
                               Recall=recall_score(y, p, zero_division=0),
                               F1=f1_score(y, p, zero_division=0),
                               MCC=matthews_corrcoef(y, p), LogLoss=log_loss(y, oof)))
    return per_repeat

# --- run all configs; SAVE AFTER EVERY ONE so nothing is ever lost -----------
summary, detail = [], []
for name, cfg in CONFIGS:
    print(f"running: {name}", flush=True)
    per = evaluate_config(cfg)
    for i, r in enumerate(per):
        detail.append(dict(config=name, repeat=i, **r))
    row = dict(config=name, **{k: (str(v) if k == "layers" else v) for k, v in cfg.items()})
    for mname in per[0]:
        mu, h = mean_ci([r[mname] for r in per])
        row[mname] = f"{mu:.3f} +/- {h:.3f}"               # formatted for the report
        row[mname + "_mean"] = round(mu, 4)                 # numeric for sorting
    summary.append(row)
    pd.DataFrame(summary).to_csv("nn_tuning_results.csv", index=False)     # incremental save
    pd.DataFrame(detail).to_csv("nn_tuning_per_repeat.csv", index=False)   # full per-repeat record

# --- final ranked summary ----------------------------------------------------
res = pd.DataFrame(summary).sort_values("MCC_mean", ascending=False)
print("\nRanked by MCC (mean over", REPEATS, "repeats):\n")
print(res[["config", "MCC", "PR_AUC", "ROC_AUC", "F1", "LogLoss"]].to_string(index=False))
