# -*- coding: utf-8 -*-
"""Double-MAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyqvR65INt5z1hiHml5nlO_aVk7OC5yV
"""

import numpy as np
import pandas as pd
from scipy.stats.mstats import hdquantiles

MIN_WELLS = 10
THRESHOLD = 3


def hdmad_outlier_limits(x, threshold=2.5):
    """Harrell–Davis median with asymmetric Double MAD limits."""

    x = pd.Series(x).dropna().astype(float)

    if len(x) < 3:
        return np.nan, np.nan, np.nan

    median = float(hdquantiles(x, prob=[0.5])[0])
    deviations = abs(x - median)

    lower_dev = deviations[x <= median]
    upper_dev = deviations[x >= median]

    lower_mad = 1.4826 * float(
        hdquantiles(lower_dev, prob=[0.5])[0]
    )

    upper_mad = 1.4826 * float(
        hdquantiles(upper_dev, prob=[0.5])[0]
    )

    lower_limit = median - threshold * lower_mad
    upper_limit = median + threshold * upper_mad

    return median, lower_limit, upper_limit


wide = pd.read_csv("low_activity_wells_flagged (2).csv")
good = wide["QC_low_activity"].eq("pass")

ids = [
    "Barcode",
    "Plate",
    "Timepoint_dpp",
    "Well",
    "Control",
    "QC_low_activity",
    "Double_MAD_HD_outlier",
    "outlier_features",
    "n_features_flagged"
]

features = [
    c for c in wide.select_dtypes(include=np.number).columns
    if c not in ids
]

outlier = pd.Series(False, index=wide.index)

low_hits = pd.DataFrame(
    False,
    index=wide.index,
    columns=features
)

high_hits = pd.DataFrame(
    False,
    index=wide.index,
    columns=features
)

limits = []


for (plate, dpp), grp in wide.groupby(
    ["Plate", "Timepoint_dpp"]
):

    here = (
        wide["Plate"].eq(plate)
        & wide["Timepoint_dpp"].eq(dpp)
        & good
    )

    for f in features:

        v = grp[f].dropna()

        if len(v) < MIN_WELLS:
            continue

        median, lower, upper = hdmad_outlier_limits(
            v,
            threshold=THRESHOLD
        )

        if pd.isna(lower) or pd.isna(upper):
            continue

        limits.append({
            "Plate": plate,
            "Timepoint_dpp": dpp,
            "Feature": f,
            "HD_median": median,
            "Lower_limit": lower,
            "Upper_limit": upper,
            "Threshold": THRESHOLD,
            "Number_of_wells": len(v)
        })

        current_low = here & good & wide[f].lt(lower)
        current_high = here & wide[f].gt(upper)

        low_hits.loc[current_low, f] = True
        high_hits.loc[current_high, f] = True

        outlier |= current_low | current_high


wide["Double_MAD_HD_outlier"] = "dead_well"
wide.loc[good & outlier, "Double_MAD_HD_outlier"] = 1
wide.loc[good & ~outlier, "Double_MAD_HD_outlier"] = 0


wide["outlier_features"] = [
    "; ".join(
        [f"{f} (low)" for f in features if low_hits.at[i, f]]
        + [f"{f} (high)" for f in features if high_hits.at[i, f]]
    )
    for i in wide.index
]


wide["n_features_flagged"] = (
    low_hits.sum(axis=1)
    + high_hits.sum(axis=1)
).astype(int)


# Save complete well-level results
wide.to_csv(
    "double_mad_hd_outliers_threshold_3.csv",
    index=False
)


# Create and save feature-limit table
limits_df = pd.DataFrame(limits)

limits_df[
    ["HD_median", "Lower_limit", "Upper_limit"]
] = limits_df[
    ["HD_median", "Lower_limit", "Upper_limit"]
].round(3)

limits_df.to_csv(
    "double_mad_hd_feature_limits_threshold_3.csv",
    index=False
)


print(
    wide["Double_MAD_HD_outlier"]
    .value_counts()
    .to_string()
)

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import math

plate_rows = "ABCDEF"
plate_cols = range(1, 9)

groups = (
    wide[["Plate", "Timepoint_dpp"]]
    .drop_duplicates()
    .sort_values(["Plate", "Timepoint_dpp"])
)


n_groups = len(groups)
n_cols = 3
n_rows = math.ceil(n_groups / n_cols)

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(13, 3.5 * n_rows)
)

axes = np.array(axes).reshape(-1)


for ax, (_, group) in zip(axes, groups.iterrows()):

    plate = group["Plate"]
    dpp = group["Timepoint_dpp"]

    data = wide[
        wide["Plate"].eq(plate)
        & wide["Timepoint_dpp"].eq(dpp)
    ].drop_duplicates("Well").set_index("Well")


    for y, plate_row in enumerate(plate_rows):

        for x in plate_cols:

            well = f"{plate_row}{x}"

            if well not in data.index:
                colour = "lightgray"

            elif (
                data.loc[well, "Double_MAD_HD_outlier"]
                == "dead_well"
            ):
                colour = "darkgray"

            elif (
                data.loc[well, "Double_MAD_HD_outlier"]
                == "yes"
            ):
                colour = "red"

            else:
                colour = "green"

            ax.scatter(
                x,
                y,
                s=550,
                c=colour,
                edgecolors="black"
            )


    ax.set(
        title=f"Plate {int(plate)} — {int(dpp)} dpp",
        xticks=list(plate_cols),
        yticks=range(6),
        yticklabels=list(plate_rows),
        xlim=(0.5, 8.5),
        ylim=(5.5, -0.5)
    )

    ax.xaxis.tick_top()
    ax.set_aspect("equal")
    ax.tick_params(length=0)


# Hide unused subplot panels
for ax in axes[n_groups:]:
    ax.axis("off")


legend = [
    Line2D(
        [0], [0],
        marker="o",
        color="w",
        markerfacecolor="green",
        markeredgecolor="black",
        markersize=12,
        label="Pass"
    ),
    Line2D(
        [0], [0],
        marker="o",
        color="w",
        markerfacecolor="red",
        markeredgecolor="black",
        markersize=12,
        label="Outlier"
    ),
    Line2D(
        [0], [0],
        marker="o",
        color="w",
        markerfacecolor="lightgray",
        markeredgecolor="black",
        markersize=12,
        label="Not in data"
    ),
    Line2D(
        [0], [0],
        marker="o",
        color="w",
        markerfacecolor="darkgray",
        markeredgecolor="black",
        markersize=12,
        label="Dead well"
    )
]


fig.legend(
    handles=legend,
    loc="lower center",
    ncol=4
)

fig.suptitle(
    "Double MAD Harrell–Davis quality control results",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout(rect=[0, 0.08, 1, 0.95])
fig.subplots_adjust(hspace=0.3)

plt.savefig(
    "Double_MAD_HD_outlier_plate_map_threshold_3.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import numpy as np
import pandas as pd
from scipy.stats.mstats import hdquantiles

MIN_WELLS = 10
THRESHOLDS = [1.0, 1.5, 2.0, 2.5, 3.0]


def hdmad_limits(x, threshold):
    x = pd.Series(x).dropna().astype(float)

    if len(x) < 3:
        return None

    med = float(hdquantiles(x, prob=[0.5])[0])
    dev = abs(x - med)

    low_mad = 1.4826 * float(
        hdquantiles(dev[x <= med], prob=[0.5])[0]
    )
    high_mad = 1.4826 * float(
        hdquantiles(dev[x >= med], prob=[0.5])[0]
    )

    return (
        med,
        med - threshold * low_mad,
        med + threshold * high_mad
    )


wide = pd.read_csv("low_activity_wells_flagged (2).csv")
#good = wide["QC_low_activity"].eq("pass")

exclude = [
    "Barcode", "Plate", "Timepoint_dpp", "Well", "Control",
    "QC_low_activity", "Double_MAD_HD_outlier",
    "outlier_features", "n_features_flagged"
]

features = [
    c for c in wide.select_dtypes(include=np.number).columns
    if c not in exclude
]

comparison = []
all_results = []

for threshold in THRESHOLDS:

    outlier = pd.Series(False, index=wide.index)
    feature_count = 0

    for (plate, dpp), grp in wide.groupby(
        ["Plate", "Timepoint_dpp"]
    ):

        here = (
            wide["Plate"].eq(plate)
            & wide["Timepoint_dpp"].eq(dpp)
        )

        for feature in features:

            values = grp[feature].dropna()

            if len(values) < MIN_WELLS:
                continue

            result = hdmad_limits(values, threshold)

            if result is None:
                continue

            median, lower, upper = result

            low = here & wide[feature].lt(lower)
            high = here & wide[feature].gt(upper)
            flagged = low | high

            outlier |= flagged
            feature_count += int(flagged.sum())

            for i in wide.index[flagged]:
                all_results.append({
                    "Threshold": threshold,
                    "Plate": plate,
                    "Timepoint_dpp": dpp,
                    "Well": wide.loc[i, "Well"],
                    "Feature": feature,
                    "Value": wide.loc[i, feature],
                    "Direction": "low" if low.loc[i] else "high",
                    "HD_median": median,
                    "Lower_limit": lower,
                    "Upper_limit": upper
                })

    column = f"DoubleMAD_T_{str(threshold).replace('.', '_')}"

    wide[column] = "dead_well"
    wide.loc[~outlier, column] = "pass"
    wide.loc[outlier, column] = "fail"

    comparison.append({
        "Threshold": threshold,
        "Outlier_wells": int(outlier.sum()),
        "Feature_outliers": feature_count
    })


comparison_df = pd.DataFrame(comparison)
results_df = pd.DataFrame(all_results)

wide.to_csv(
    "double_mad_threshold_sensitivity.csv",
    index=False
)

comparison_df.to_csv(
    "double_mad_threshold_comparison.csv",
    index=False
)

results_df.to_csv(
    "double_mad_all_threshold_outliers.csv",
    index=False
)

print(comparison_df)

import plotly.express as px

fig = px.line(
    comparison_df,
    x="Threshold",
    y=["Outlier_wells", "Feature_outliers"],
    markers=True,
    title="Double MAD Threshold Comparison"
)

fig.show()
