# -*- coding: utf-8 -*-
"""labelling_unsupervised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYX1vZ1PfKKaBTYIvNqIn5VaX9qekLWV
"""

"""4-detector consensus pseudo-labels for tier-2 QC (ECOD, Isolation Forest, KNN, HBOS).
Requires: pandas scikit-learn pyod"""
!pip install pyod
import numpy as np, pandas as pd
from sklearn.preprocessing import StandardScaler
from pyod.models.ecod import ECOD          # tail / empirical-CDF (skew-aware)
from pyod.models.iforest import IForest    # isolation ensemble (no distributional assumption)
from pyod.models.knn import KNN            # distance-based (far from neighbours)
from pyod.models.hbos import HBOS          # histogram-based (fast, skew-tolerant)

CONTAM = 0.15   # fraction each detector flags; sets the per-detector operating point

# --- load and keep only analysable wells (passed tier-1) -------------------
META  = ["Barcode","Plate","Timepoint_dpp","Well","Control","QC_low_activity","qc_fail"]
d = pd.read_csv("MEA_data.csv").query("QC_low_activity == 'pass'").reset_index(drop=True)
GROUP = ["Barcode","Plate","Timepoint_dpp"]                 # one batch = one recording
feats = [c for c in d.columns if c not in META and pd.api.types.is_numeric_dtype(d[c])]

# --- within-batch robust standardisation (median/IQR), then scale ----------
def robust_z(s):                                            # (x-median)/IQR, resists skew
    iqr = s.quantile(.75) - s.quantile(.25); return (s - s.median()) / (iqr if iqr else 1.0)
Z = d.groupby(GROUP)[feats].transform(robust_z).fillna(0.0)   # NaN (no bursts) -> 0 = neutral post-standardisation
X = StandardScaler().fit_transform(Z.to_numpy())

# --- run the four detectors ------------------------------------------------
detectors = {"ECOD": ECOD(contamination=CONTAM),
             "IForest": IForest(contamination=CONTAM, n_estimators=200, random_state=42),
             "KNN": KNN(contamination=CONTAM, n_neighbors=5),
             "HBOS": HBOS(contamination=CONTAM)}
for name, m in detectors.items():
    m.fit(X)
    d[f"score_{name}"] = m.decision_scores_                 # continuous anomaly score
    d[f"flag_{name}"]  = m.labels_                          # 0/1 flag at the contamination cut-off

# --- consensus vote (0-4) and label groups ---------------------------------
d["consensus"] = d[[f"flag_{n}" for n in detectors]].sum(axis=1)     # how many detectors agree
d["label_group"] = np.select(
    [d["consensus"] >= 4, d["consensus"] == 0],            # all four agree / none flag
    ["confident_fail", "confident_pass"], default="uncertain")

# --- save + report ---------------------------------------------------------
d.to_csv("consensus_labels.csv", index=False)
d[d.label_group == "confident_fail"][["Barcode","Plate","Timepoint_dpp","Well"]] \
    .to_csv("confident_fail_wells_for_lab.csv", index=False)         # list to send to the lab

print("consensus distribution (0-4):", d["consensus"].value_counts().sort_index().to_dict())
print("groups:", d["label_group"].value_counts().to_dict())
if "qc_fail" in d.columns:                                 # optional agreement check
    ref = (d["qc_fail"].astype(str) == "1").astype(int)
    ov = int(((d.consensus >= 4) & (ref == 1)).sum())
    print(f"confident_fail overlap with existing qc_fail: {ov} of {int(ref.sum())}")