# -*- coding: utf-8 -*-
"""ROUT_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVggJuEJCc3W6_Lm7H-BYGfAlFxiE-dp
"""

import numpy as np
import pandas as pd
from scipy.stats import t

Q = 0.01
MIN_WELLS = 10


def rout(x, q=0.01):
    x = pd.Series(x).dropna().astype(float)
    n = len(x)

    if n < 3:
        return None

    m = x.median()

    # Lorentzian robust fit for constant model Y = M
    for _ in range(100):
        r = x - m
        rsdr = np.percentile(abs(r), 68.27) * np.sqrt(n / (n - 1))

        if rsdr == 0:
            return None

        w = 1 / (1 + (r / rsdr) ** 2)
        new_m = np.average(x, weights=w)

        if abs(new_m - m) < 1e-8:
            break

        m = new_m

    r = x - m
    rsdr = np.percentile(abs(r), 68.27) * np.sqrt(n / (n - 1))
    z = abs(r) / rsdr
    p = 2 * t.sf(z, df=n - 1)

    result = pd.DataFrame({
        "Value": x,
        "Residual": r,
        "RSDR": rsdr,
        "T_ratio": z,
        "P_value": p,
        "Direction": np.where(r < 0, "low", "high"),
        "Outlier": False
    }).sort_values("T_ratio")

    result["Rank"] = range(1, n + 1)
    result["Alpha"] = q * (n - result["Rank"] + 1) / n

    tested = result[result["Rank"] >= np.floor(0.7 * n)]

    hit = tested[tested["P_value"] < tested["Alpha"]]

    if not hit.empty:
        cutoff = hit.iloc[0]["T_ratio"]
        result["Outlier"] = result["T_ratio"] >= cutoff

    return result.sort_index()

wide = pd.read_csv("low_activity_wells_flagged (2).csv")
good = wide["QC_low_activity"]#.eq("pass")

exclude = ["Plate", "Timepoint_dpp", "Well"]
features = wide.select_dtypes("number").columns.difference(exclude)

low_hits = pd.DataFrame(False, index=wide.index, columns=features)
high_hits = low_hits.copy()
outlier = pd.Series(False, index=wide.index)
results = []

for (plate, dpp), g in wide.groupby(["Plate", "Timepoint_dpp"]):

    for feature in features:

        if g[feature].notna().sum() < MIN_WELLS:
            continue

        r = rout(g[feature], Q)

        if r is None:
            continue

        for i, row in r[r["Outlier"]].iterrows():

            low_hits.loc[i, feature] = row["Direction"] == "low"
            high_hits.loc[i, feature] = row["Direction"] == "high"
            outlier.loc[i] = True

            results.append([
                plate, dpp, wide.loc[i, "Well"], feature,
                row["Value"], row["Direction"],
                row["T_ratio"], row["P_value"], row["Alpha"]
            ])

wide["ROUT_outlier"] = "dead_well"
wide.loc[outlier, "ROUT_outlier"] = "yes"
wide.loc[~outlier, "ROUT_outlier"] = "no"

wide["outlier_features"] = [
    "; ".join(
        [f"{f} (low)" for f in features if low_hits.at[i, f]] +
        [f"{f} (high)" for f in features if high_hits.at[i, f]]
    )
    for i in wide.index
]

wide["n_features_flagged"] = (
    low_hits.sum(axis=1) + high_hits.sum(axis=1)
).astype(int)

rout_outliers = pd.DataFrame(results, columns=[
    "Plate", "Timepoint_dpp", "Well", "Feature",
    "Value", "Direction", "T_ratio", "P_value", "Alpha"
])

wide.to_csv("ROUT_QC_results_Q=0.01.csv", index=False)
rout_outliers.to_csv("ROUT_feature_outliers_Q=0.01.csv", index=False)

print(wide["ROUT_outlier"].value_counts())
print(len(rout_outliers), "feature outliers found")

import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

rows = "ABCDEF"
cols = range(1, 9)

groups = (
    wide[["Plate", "Timepoint_dpp"]]
    .drop_duplicates()
    .sort_values(["Plate", "Timepoint_dpp"])
)

ncols = 3
nrows = math.ceil(len(groups) / ncols)

fig, axes = plt.subplots(
    nrows,
    ncols,
    figsize=(13, 3.5 * nrows)
)

axes = np.array(axes).ravel()

for ax, (_, g) in zip(axes, groups.iterrows()):

    d = (
        wide[
            (wide["Plate"] == g["Plate"]) &
            (wide["Timepoint_dpp"] == g["Timepoint_dpp"])
        ]
        .drop_duplicates("Well")
        .set_index("Well")
    )

    for y, r in enumerate(rows):
        for x in cols:

            well = f"{r}{x}"

            if well not in d.index:
                colour = "lightgray"

            elif d.loc[well, "ROUT_outlier"] == "dead_well":
                colour = "darkgray"

            elif d.loc[well, "ROUT_outlier"] == "yes":
                colour = "red"

            else:
                colour = "green"

            ax.scatter(
                x, y,
                s=550,
                c=colour,
                edgecolors="black"
            )

    ax.set(
        title=f"Plate {int(g['Plate'])} — {int(g['Timepoint_dpp'])} dpp",
        xticks=list(cols),
        yticks=range(6),
        yticklabels=list(rows),
        xlim=(0.5, 8.5),
        ylim=(5.5, -0.5)
    )

    ax.xaxis.tick_top()
    ax.set_aspect("equal")
    ax.tick_params(length=0)

# Hide unused panels
for ax in axes[len(groups):]:
    ax.axis("off")

legend = [
    Line2D([0],[0], marker="o", color="w",
           markerfacecolor="green", markeredgecolor="black",
           markersize=12, label="Pass"),

    Line2D([0],[0], marker="o", color="w",
           markerfacecolor="red", markeredgecolor="black",
           markersize=12, label="Fail"),

    Line2D([0],[0], marker="o", color="w",
           markerfacecolor="lightgray", markeredgecolor="black",
           markersize=12, label="Not in data"),

    Line2D([0],[0], marker="o", color="w",
           markerfacecolor="darkgray", markeredgecolor="black",
           markersize=12, label="Dead well")
]

fig.legend(handles=legend, loc="lower center", ncol=4)

fig.suptitle(
    "ROUT Quality Control Results(Q=0.01)",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout(rect=[0, 0.08, 1, 0.95])
fig.subplots_adjust(hspace=0.3)

plt.savefig("ROUT_outlier_plate_map_Q=0.05.png", dpi=300)

plt.show()

Q_VALUES = [0.001, 0.01, 0.05, 0.10]

comparison = []
all_results = []

for q in Q_VALUES:

    outlier = pd.Series(False, index=wide.index)
    feature_results = []

    for (plate, dpp), g in wide.groupby(
        ["Plate", "Timepoint_dpp"]
    ):
        for feature in features:

            if g[feature].notna().sum() < MIN_WELLS:
                continue

            r = rout(g[feature], q)

            if r is None:
                continue

            flagged = r[r["Outlier"]]

            for i, row in flagged.iterrows():

                outlier.loc[i] = True

                feature_results.append({
                    "Q": q,
                    "Plate": plate,
                    "Timepoint_dpp": dpp,
                    "Well": wide.loc[i, "Well"],
                    "Feature": feature,
                    "Direction": row["Direction"],
                    "Value": row["Value"],
                    "T_ratio": row["T_ratio"],
                    "P_value": row["P_value"]
                })

    comparison.append({
        "Q": q,
        "Feature_outliers": len(feature_results),
        "Outlier_wells": outlier.sum()
    })

    all_results.extend(feature_results)


comparison_df = pd.DataFrame(comparison)
all_results_df = pd.DataFrame(all_results)

comparison_df.to_csv(
    "ROUT_Q_comparison.csv",
    index=False
)

all_results_df.to_csv(
    "ROUT_all_Q_results.csv",
    index=False
)

comparison_df

import plotly.express as px

fig = px.line(
    comparison_df,
    x="Q",
    y=["Feature_outliers", "Outlier_wells"],
    markers=True,
    title="Comparison of ROUT Q Values"
)

fig.show()
fig.write_html("ROUT_Q_comparison.html")

for q in Q_VALUES:

    outlier = pd.Series(False, index=wide.index)

    for (plate, dpp), g in wide.groupby(
        ["Plate", "Timepoint_dpp"]
    ):
        for feature in features:

            if g[feature].notna().sum() < MIN_WELLS:
                continue

            r = rout(g[feature], q)

            if r is not None:
                outlier.loc[r.index[r["Outlier"]]] = True

    column = f"ROUT_Q_{str(q).replace('.', '_')}"

    wide[column] = "dead_well"
    wide.loc[~outlier, column] = "pass"
    wide.loc[outlier, column] = "fail"


wide.to_csv(
    "ROUT_Q_sensitivity_results.csv",
    index=False
)

qc_columns = [
    c for c in wide.columns
    if c.startswith("ROUT_Q_")
]

wide[
    ["Plate", "Timepoint_dpp", "Well"] + qc_columns
].head(20)
