# -*- coding: utf-8 -*-
"""unsupervised_outlier_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDGdJGUOtEDnKI8B-Jy4IOsgAMQ-1knb
"""

!pip install pyod
import pandas as pd
from sklearn.impute import SimpleImputer
from pyod.models.hbos import HBOS       # histogram baseline — simple/fast, per-feature
from pyod.models.ecod import ECOD       # empirical-CDF tails; SKEW-AWARE (fits our right-skew)
from pyod.models.copod import COPOD     # copula tails; parameter-free, interpretable
from pyod.models.iforest import IForest # isolation ensemble; no distributional assumption

# --- load and screen -------------------------------------------------------
# META = columns that IDENTIFY a well but are NOT measurements -> never modelled.
META = ["Barcode", "Plate", "Timepoint_dpp", "Well", "Control"]
# Keep only wells that PASSED tier-1: tier 2 hunts for *abnormal* wells among the
# live ones, so dead / low-activity wells must be removed first or they dominate.
d = (pd.read_csv("low_activity_wells_flagged_labeled.csv")
       .query("QC_low_activity == 'pass'")
       .reset_index(drop=True))

# --- choose the feature columns -------------------------------------------
# Every numeric column that is not metadata or the QC flag = an electrophysiology
# feature. Auto-detecting keeps the script working if the feature set changes.
feats = [c for c in d.columns
         if c not in META + ["QC_low_activity"]
         and pd.api.types.is_numeric_dtype(d[c])]

# --- account for plate / timepoint batch differences -----------------------
# Different plates and days-post-plating sit at systematically different feature
# LEVELS (a batch effect: one line/plate looked "abnormal" simply for being a
# different batch). To judge each well against its OWN batch, robustly standardise
# every feature WITHIN each recording (Barcode x Plate x Timepoint): subtract the
# group median and divide by the group IQR — both resistant to the right-skew.
# The detectors then flag wells odd relative to their platemates, not whole plates.
GROUP = ["Barcode", "Plate", "Timepoint_dpp"]      # set GROUP = None to score globally
def _robust_z(s):                                   # (x - median) / IQR, per feature
    iqr = s.quantile(.75) - s.quantile(.25)
    return (s - s.median()) / (iqr if iqr else 1.0) # guard against zero-IQR features
feat_df = d.groupby(GROUP)[feats].transform(_robust_z) if GROUP else d[feats]

# --- handle missing values -------------------------------------------------
# Network-burst features are NaN for wells that never burst, and the models
# can't take NaN. Impute the per-feature MEDIAN: it's robust to the heavy
# right-skew, whereas the mean would be dragged up by the long tail.
X = SimpleImputer(strategy="median").fit_transform(feat_df)

# --- score every well with each detector -----------------------------------
# random_state fixes Isolation Forest so results are reproducible; the other
# three are deterministic. Default contamination (0.1) flags the top 10% — a
# PROVISIONAL cut-off, only meaningful until the labels set a real threshold.
models = {"HBOS": HBOS(), "ECOD": ECOD(), "COPOD": COPOD(),
          "IForest": IForest(random_state=42)}

out = d[META].copy()                             # build the results table from the IDs
for name, m in models.items():
    m.fit(X)
    out[f"score_{name}"] = m.decision_scores_    # continuous anomaly score (higher = odder)
    out[f"flag_{name}"]  = m.labels_             # 0/1 flag at the contamination cut-off

# Consensus: how many of the four call each well an outlier (0–4). A high count
# = a well every method agrees is abnormal — the robust core worth trusting.
out["n_flagged"] = out.filter(like="flag_").sum(axis=1)
out.to_csv("unsupervised_well_scores_group_aware.csv", index=False)
print(out["n_flagged"].value_counts().sort_index())

# --- evaluation (activates automatically once the labels are added) --------
# Set LABEL_COL to a 0/1 column in the CSV (1 = a well the experts failed).
# We report PR-AUC and MCC rather than accuracy/ROC because the labels will be
# IMBALANCED (few fails), where those two give the honest picture. Each detector's
# continuous score is judged as a ranking of "how likely this well is a fail".
LABEL_COL = "qc_fail"
if LABEL_COL in d.columns:
    from sklearn.metrics import (roc_auc_score, average_precision_score,
                                 matthews_corrcoef)
    y = d[LABEL_COL]
    print(f"\n{'method':8s} ROC-AUC  PR-AUC   MCC")
    for name in models:
        print(f"{name:8s} "
              f"{roc_auc_score(y, out['score_'+name]):.3f}    "        # ranking quality
              f"{average_precision_score(y, out['score_'+name]):.3f}    "  # PR-AUC (imbalance-safe)
              f"{matthews_corrcoef(y, out['flag_'+name]):.3f}")        # agreement at the flag
else:
    print(f"\n[no '{LABEL_COL}' column yet — add the labels to evaluate]")