# -*- coding: utf-8 -*-
"""rf_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stMBFabZreqiCCX7nPg7rsIQjYLt9fw_
"""

# =======================================================================
# Tier-2 model — train once on the labelled wells and save
# =======================================================================
import joblib
from sklearn.ensemble import RandomForestClassifier

TRAIN_FILE = "MEA_data_consensus_training_vote2.csv"   # 149 labelled wells (23 fail / 126 pass)
MODEL_FILE = "tier2_rf_model.joblib"

td = pd.read_csv(TRAIN_FILE)
META  = ["Barcode", "Plate", "Timepoint_dpp", "Well", "Control", "QC_low_activity", "qc_fail"]
feats = [c for c in td.columns if c not in META and pd.api.types.is_numeric_dtype(td[c])]

# burst features are NaN when a well never bursted: add a flag, fill 0 (same as in evaluation)
burst = [c for c in feats if td[c].isna().any()]
td["bursted"] = td[burst[0]].notna().astype(int)
td[burst] = td[burst].fillna(0.0)
feats = feats + ["bursted"]

Xtr = td[feats].to_numpy(float)
ytr = (td["qc_fail"].astype(str) == "1").astype(int).to_numpy()          # 1 = fail

rf = RandomForestClassifier(n_estimators=500, max_depth= None, max_features='log2', min_samples_leaf= 6, class_weight="balanced_subsample", random_state=42)
rf.fit(Xtr, ytr)

# save the model together with the exact feature list and burst columns it was trained on
joblib.dump({"model": rf, "feats": feats, "burst": burst}, MODEL_FILE)
print("Trained on", len(td), "wells; saved model to", MODEL_FILE)